- name: Ensure commands can be executed as www-data - set shell
  user: name=www-data shell=/bin/false

- name: Copy jira init script
  copy: src=jira.service dest=/etc/systemd/system/jira.service
  notify:
    - restart jira

- name: enable jira
  systemd:
    name: jira
    enabled: yes
    daemon_reload: yes

