- name: mount /var/www
  mount: name=/var/www src=/dev/vdb1 fstype=ext4 state=mounted
  when: "inventory_hostname not in excluded_mounts"

- name: Install prerequisite packages
  apt: 
    pkg: [mysql-client, postfix]
    state: present
    update_cache: yes
    cache_valid_time: 18000

- name: Copy nginx global configuration
  synchronize: src="global/" dest=/etc/nginx/global checksum=yes delete=yes owner=no group=no
  notify:
    - restart nginx

- name: Copy nginx sites configuration
  synchronize: src="sites/{{ inventory_hostname }}/" dest=/etc/nginx/sites-enabled checksum=yes delete=yes owner=no group=no
  notify:
    - restart nginx

- name: Copy nginx SSL certificates
  synchronize: src="ssl/{{ inventory_hostname }}/" dest=/etc/nginx/ssl checksum=yes delete=yes owner=no group=no
  notify:
    - restart nginx

- name: Apache | Check if apache should be setup - are configuration files present?
  local_action: stat path="roles/nginx/files/apache/{{ inventory_hostname }}/"
  register: apache_config_files

- name: Apache | Install apache2
  apt:
    pkg: 'apache2'
    state: installed
    update_cache: yes
    cache_valid_time: 18000
  when: apache_config_files.stat.exists == True

- name: Apache | Activate cgid module
  apache2_module:
    state: present
    name: cgid
  when: apache_config_files.stat.exists == True
  notify:
    - restart apache

- name: Apache | Copy apache configuration
  synchronize: src="apache/{{ inventory_hostname }}/ports.conf" dest=/etc/apache2 checksum=yes owner=no group=no
  when: apache_config_files.stat.exists == True
  notify:
    - restart apache

- name: chown www-data /var/www
  file: path=/var/www mode=750 owner=www-data group=www-data state=directory

- name: mkdir /var/www/log
  file: path=/var/www/log mode=750 state=directory
