- name: mount /var/www
  mount: name=/var/www src=/dev/vdb1 fstype=ext4 state=mounted
  when: "inventory_hostname not in excluded_mounts"

- name: Install prerequisite packages
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=18000
  with_items:
    - mysql-client
    - postfix

- name: Use customized php.ini for FPM (improvement  for geerlingy role)
  file: src=/etc/php5/php.ini dest=/etc/php5/fpm/php.ini state=link force=yes
  notify:
    - restart php-fpm

- name: Copy nginx global configuration
  synchronize: src="global/" dest=/etc/nginx/global checksum=yes delete=yes owner=no group=no
  notify:
    - restart nginx

- name: Copy nginx sites configuration
  synchronize: src="sites/{{ inventory_hostname }}/" dest=/etc/nginx/sites-enabled checksum=yes delete=yes owner=no group=no
  notify:
    - restart nginx

- name: Copy nginx SSL certificates
  synchronize: src="ssl/{{ inventory_hostname }}/" dest=/etc/nginx/ssl checksum=yes delete=yes owner=no group=no
  notify:
    - restart nginx

- name: chown www-data /var/www
  file: path=/var/www mode=750 owner=www-data group=www-data state=directory

- name: mkdir /var/www/log
  file: path=/var/www/log mode=750 state=directory
