---
- hosts: all
  vars:
    - backup__tarsnap_cachedir: /var/tarsnap/cache
    - backup__rebuild_cache: false
    - github_users:
      - name: antoviaque
        groups: sudo
  roles:
    - common
    - { role: geerlingguy.security, security_sudoers_passwordless: [ubuntu] }
    - geerlingguy.github-users
    - users
    - { role: oefenweb.swapfile, swapfile_size: 2GB }
    - tarsnap
    - coaxial.backup

- hosts: mysql
  roles:
    - mysql # mount must happen before package installation
    - geerlingguy.mysql

- hosts: mail
  vars:
    - letsencrypt_email: xavier+letsencrypt@antoviaque.org
    - letsencrypt_domains: ['mail.plebia.org']
  roles:
    - postfix
    - courier
    - SoInteractive.letsencrypt

- hosts: webservers
  vars:
    - excluded_mounts: ['mail', 'media']
    - nginx_remove_default_vhost: true
    - php_memory_ilimit: "128M"
    - php_max_execution_time: "90"
    - php_upload_max_filesize: "256M"
    - php_enable_php_fpm: true
    - php_webserver_daemon: "nginx"
    - php_default_version_debian: "7.2"
    - php_mysql_package: "php7.2-mysql"
  roles:
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.php-mysql
    - nginx
 
- hosts: discourse
  roles:
    - angstwad.docker_ubuntu
    - discourse

- hosts: opencraft-tasks
  vars:
    - java_oracle_distribution: jre
    - github_users:
      - name: bradenmacdonald
        groups: sudo
  roles:
    - geerlingguy.github-users
    - geerlingguy.java
    - jira

- hosts: media
  roles:
    - media
