---
- hosts: all
  roles:
    - common
    - users
    - { role: geerlingguy.security, security_sudoers_passwordless: [ubuntu] }
    - { role: kamaln7.swapfile, swapfile_size: 2GB }

- hosts: mysql
  roles:
    - mysql # mount must happen before package installation
    - geerlingguy.mysql

- hosts: postgresql
  roles:
    - postgresql # mount must happen before package installation
    - ANXS.postgresql

- hosts: mail
  roles:
    - postfix
    - courier

- hosts: webservers
  roles:
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.php-mysql
    - nginx

- hosts: opencraft-tasks
  vars:
    - java_oracle_distribution: jre
  roles:
    - groover.java
    - jira

- hosts: cardstories
  roles:
    - cardstories

- hosts: media
  roles:
    - media
