---
- hosts: all
  vars:
    - tarsnap_cache: /var/tarsnap/cache
    - tarsnap_cron_hour: "5"
    - tarsnap_tarsnapper_conf: "../../tarsnap/files/conf/tarsnapper.{{ inventory_hostname }}.conf"
  roles:
    - common
    - users
    - { role: geerlingguy.security, security_sudoers_passwordless: [ubuntu] }
    - { role: kamaln7.swapfile, swapfile_size: 2GB }
    - pmbauer.tarsnap
    - tarsnap

- hosts: mysql
  roles:
    - mysql # mount must happen before package installation
    - geerlingguy.mysql

- hosts: postgresql
  roles:
    - postgresql # mount must happen before package installation
    - ANXS.postgresql

- hosts: mail
  roles:
    - postfix
    - courier

- hosts: webservers
  vars:
    - excluded_mounts: ['media']
    - nginx_remove_default_vhost: true
    - php_memory_ilimit: "128M"
    - php_max_execution_time: "90"
    - php_upload_max_filesize: "256M"
    - php_version: "5.5"
    - php_enable_php_fpm: true
    - php_webserver_daemon: "nginx"
    - php_packages:
      - php5-common
      - php5-fpm
      - php5-cli
      - php5-dev
      - libpcre3-dev
      - php5-gd
      - php5-curl
      - php5-imap
      - php5-json
    - php_mysql_package: php5-mysql
  roles:
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.php-mysql
    - nginx

- hosts: opencraft-tasks
  vars:
    - java_oracle_distribution: jre
  roles:
    - groover.java
    - jira

- hosts: cardstories
  roles:
    - cardstories

- hosts: media
  roles:
    - media
