---
- hosts: edx*
  vars:
    http_port: 80
    max_clients: 200
  user: root
  tasks:
  - name: ensure nginx is at the latest version
    apt: pkg=nginx state=latest
  - name: write a test file
    template: src=test.j2 dest=/tmp/test.txt
    notify:
    - restart nginx
  - name: ensure nginx is running
    service: name=nginx state=started
  handlers:
    - name: restart nginx
      action: service name=nginx state=restarted
