- name: Install system packages
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=18000
  with_items:
    - postfix
    - postfix-mysql
    - postgrey
    - mysql-client
    - mailman

- name: Create mailbox group
  group: name=mailbox gid=2500 system=yes

- name: Create mailbox user
  user: name=mailbox uid=2500 group=mailbox system=yes

- name: mount /mailbox
  mount: name=/mailbox src=/dev/vdb1 fstype=ext4 state=mounted

- name: chown /mailbox
  file: path=/mailbox owner=mailbox group=mailbox state=directory

- name: chmod /mailbox
  file: path=/mailbox mode=755 state=directory

- name: Copy postfix configuration
  synchronize: src="etc/" dest=/etc checksum=yes owner=no group=no
  notify:
    - run newaliases
    - run postmap
    - restart postgrey
    - restart postfix

- name: Generate postfix configuration templates
  template: src="{{ item }}.j2" dest="/{{ item }}" owner=root group=postfix mode=0640
  with_items:
    - etc/postfix/mysql_virtual_alias_maps.cf
    - etc/postfix/mysql_virtual_domains_maps.cf
    - etc/postfix/mysql_virtual_mailbox_maps.cf
    - etc/postfix/sasl_passwd
  notify:
    - restart postfix

- name: Mailman | Check the status of /var/lib/mailman - we want to use /mailbox/mailman for this
  stat: path=/var/lib/mailman
  register: var_lib_mailman
 
- name: Mailman | Keep an archive of the distribution's /var/lib/mailman
  command: mv /var/lib/mailman /var/lib/mailman.dist
  when: var_lib_mailman.stat.isdir is defined and var_lib_mailman.stat.isdir

- name: Mailman | Create symbolic link to /mailbox/mailman
  file:
    src: /mailbox/mailman
    dest: /var/lib/mailman
    state: link
  when: var_lib_mailman.stat.isdir is defined and var_lib_mailman.stat.isdir
  notify:
    - restart mailman

- name: Mailman | Check the status of /etc/letsencrypt - we want to use /mailbox/letsencrypt for this
  stat: path=/etc/letsencrypt
  register: etc_letsencrypt
 
- name: Mailman | Keep an archive of the distribution's /etc/letencrypt
  command: mv /etc/letsencrypt /etc/letencrypt.dist
  when: etc_letsencrypt.stat.isdir is defined and etc_letsencrypt.stat.isdir

- name: Mailman | Create symbolic link to /etc/letsencrypt
  file:
    src: /mailbox/letsencrypt
    dest: /etc/letsencrypt
    state: link
  when: not etc_letsencrypt.stat.exists or (etc_letsencrypt.stat.isdir is defined and etc_letsencrypt.stat.isdir)
