- name: Install system packages
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=18000
  with_items:
    - postfix
    - postfix-mysql
    - postgrey
    - mysql-client

- name: Create mailbox group
  group: name=mailbox gid=2500 system=yes

- name: Create mailbox user
  user: name=mailbox uid=2500 group=mailbox system=yes

- name: mount /mailbox
  mount: name=/mailbox src=/dev/vdb1 fstype=ext4 state=mounted

- name: chown /mailbox
  file: path=/mailbox owner=mailbox group=mailbox state=directory

- name: chmod /mailbox
  file: path=/mailbox mode=750 state=directory

- name: Copy postfix configuration
  synchronize: src="etc/" dest=/etc checksum=yes
  notify:
    - run newaliases
    - run postmap
    - restart postgrey
    - restart postfix

- name: Generate postfix configuration templates
  template: src="{{ item }}.j2" dest="/{{ item }}" owner=root group=postfix mode=0640
  with_items:
    - etc/postfix/mysql_virtual_alias_maps.cf
    - etc/postfix/mysql_virtual_domains_maps.cf
    - etc/postfix/mysql_virtual_mailbox_maps.cf
    - etc/postfix/sasl_passwd
  notify:
    - restart postfix

# To configure:
#/etc/postgrey/*
