---
# Installation & update of apt system packages which are role-independent

- name: system-packages | apt-get update && dist-upgrade
  apt: upgrade=dist update_cache=yes cache_valid_time=18000

- name: system-packages | Install role-independent system packages
  apt: pkg=$item state=installed
  with_items:
    - sudo
    - vim
    - htop
    - iftop
    - iotop
    - mosh
    - zsh
    - git
    - screen
    - build-essential
    - apticron
    - apt-file
    - etckeeper
    - links

- name: system-packages | Configure git author <root@<current_host>
  shell: git config --global user.name "root" && git config --global user.email "root@{{ ansible_hostname }}"

- name: system-packages | etckeeper - Use git
  copy: src=etckeeper.conf dest=/etc/etckeeper/etckeeper.conf owner=root group=root mode=644 backup=yes

- name: system-packages | etckeeper - git init && commit
  shell: etckeeper init && etckeeper commit "Initial commit." creates=/etc/.git
