---
- name: add discourse user
  user: name=discourse groups=sudo,admin

- name: ensure docker is running
  service: name=docker state=restarted
  sudo: yes

- name: check if discourse is running
  shell: docker ps
  sudo: yes
  register: discourse_running

- name: checkout discourse source
  git: repo="https://github.com/discourse/discourse_docker.git" dest=/var/discourse update=no accept_hostkey=yes
  notify:
    - stop discourse
    - rebuild discourse

- name: copy discourse configuration app.yml
  template: src=app.yml.j2 dest=/var/discourse/containers/app.yml owner=discourse group=sudo
  notify:
    - stop discourse
    - rebuild discourse

- meta: flush_handlers

- name: restart discourse ! handler
  command: echo "start discourse"
  when: true
  notify:
    - restart discourse
