- name: Create mysql group
  group: name=mysql system=yes

- name: Create mysql user
  user: name=mysql group=mysql system=yes

- name: mount /var/lib/mysql
  mount: name=/var/lib/mysql src=/dev/vdb1 fstype=ext4 state=mounted

- name: chown -R /var/lib/mysql
  file: path=/var/lib/mysql owner=mysql group=mysql recurse=yes state=directory

- name: chmod /var/lib/mysql
  file: path=/var/lib/mysql mode=700 state=directory

- name: Install my.cnf - ubuntu
  template:
     src: my.cnf.j2
     dest: /home/ubuntu/.my.cnf
     owner: ubuntu
     group: ubuntu
     mode: '0600'

- name: Install my.cnf - root
  template:
     src: my.cnf.j2
     dest: /root/.my.cnf
     owner: root
     group: root
     mode: '0600'

