---
# Tasks related to external users access and permissions

- name: Set up authorized_keys for the ubuntu user - all servers
  authorized_key: user=ubuntu
                  key="{{ item }}"
  with_file:
    - public_keys/ansible
    - public_keys/antoviaque

- name: Set up authorized_keys for the ubuntu user - mail server
  authorized_key: user=ubuntu
                  key="{{ item }}"
  with_file:
    - public_keys/pierre
  when: inventory_hostname == 'mail'

- name: chmod 750 /root
  file: path=/root owner=root group=root mode=750 state=directory
- name: chmod 750 ~
  file: path=/home/ubuntu owner=ubuntu group=ubuntu mode=750 state=directory
- name: mkdir ~/dl
  file: path=/home/ubuntu/dl owner=ubuntu group=ubuntu mode=755 state=directory
- name: mkdir ~/src
  file: path=/home/ubuntu/src owner=ubuntu group=ubuntu mode=755 state=directory

- name: Allow password SSH login on some hosts
  lineinfile: dest=/etc/ssh/sshd_config line="PasswordAuthentication yes" regexp="^PasswordAuthentication "
  when: "inventory_hostname in sshd_allow_login_password"
  notify: reload sshd

- name: Disable password SSH login on the other hosts
  lineinfile: dest=/etc/ssh/sshd_config line="PasswordAuthentication no" regexp="^PasswordAuthentication "
  when: "inventory_hostname not in sshd_allow_login_password"
  notify: reload sshd
