- name: Set up authorized_keys for the ubuntu user
  authorized_key: user=ubuntu
                  key="{{ item }}"
  with_file:
    - ../../users/tasks/public_keys/bradenmacdonald
    - ../../users/tasks/public_keys/smarnach
    - ../../users/tasks/public_keys/omarkhan

- name: Ensure commands can be executed as www-data - set shell
  user: name=www-data shell=/bin/bash

- name: Clone the opencraft repository
  git: repo=https://github.com/open-craft/opencraft.git dest="{{ opencraft_root_dir }}" update=no

- name: Install system dependencies
  shell: make install_system_dependencies
  args:
    chdir: "{{ opencraft_root_dir }}"

- name: Install virtualenv
  pip: name=virtualenv executable=pip3

- name: Install virtualenvwrapper
  pip: name=virtualenvwrapper executable=pip3

- name: Create the opencraft virtualenv
  command: virtualenv {{ opencraft_virtualenv_dir }} -p python3.4 creates="{{ opencraft_virtualenv_dir }}"

- name: Install python requirements
  pip:
    requirements="{{ opencraft_root_dir }}/requirements.txt"
    virtualenv="{{ opencraft_virtualenv_dir }}"

- name: Install the venv wrapper script
  template: src=venv_exec.j2 dest="{{ opencraft_virtualenv_dir }}/bin/exec" mode=755

- name: Install the configuration/environment file
  copy: src=env dest="{{ opencraft_root_dir }}/.env" follow=yes

- name: "chown -R {{ opencraft_root_dir }}"
  file: path="{{ opencraft_root_dir }}" owner=www-data group=www-data recurse=yes state=directory
