- name: Set FQDN hostname
  hostname: name="{{ inventory_hostname }}.vm.plebia.org"

- name: Copy hosts file
  copy: src=hosts dest=/etc/hosts owner=root group=root mode=644

- name: apt-get update && dist-upgrade
  apt: upgrade=dist update_cache=yes cache_valid_time=18000

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Install prerequisite packages
  apt:
    pkg: ['htop', 'ntp', 'sudo', 'vim', 'iftop', 'iotop', 'mosh', 'git', 'screen', 'build-essential', 'apticron', 'apt-file', 'etckeeper', 'links', 'tree', 'pwgen', 'libxml2-dev', 'libxslt1-dev', 'python-dev', 'tmpreaper', 'intel-microcode', 'python3.7', 'python3.7-dev']
    state: installed
    update_cache: yes
    cache_valid_time: 18000

- name: Activate tmpreaper
  lineinfile: dest=/etc/tmpreaper.conf state=absent regexp="^SHOWWARNING=true"

- name: Configure git author <root@<current_host>
  shell: git config --global user.name "Xavier Antoviaque" && git config --global user.email "xavier@antoviaque.org"

- name: etckeeper - Use git
  copy: src=etckeeper.conf dest=/etc/etckeeper/etckeeper.conf owner=root group=root mode=644 backup=yes

- name: etckeeper - git init && commit
  shell: etckeeper init && etckeeper commit "Initial commit." creates=/etc/.git

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
